### ISSUE TITLE
Override order is reversed when providing functions instead of Objects

### ISSUE THREAD

**Issue by kafoso** [dfilatov/inherit#20]
In `test.js`, `exports.testOverride` verifies that the "youngest" Object (or "class") overrides the same-name function of its parent (or "base"). This test of course works.

However, if the `prop` argument is a function, the override order is reversed. See example below.

```javascript
exports.testOverrideOfFunctions = function(test) {
    test.expect(2);
    var A = inherit(function(){
      this.method = function() {
          return 'A';
      };
    });
    var B = inherit(A, function(){
      this.method = function() {
          return 'B';
      };
    });

    test.equal(new A().method(), 'A');
    test.equal(new B().method(), 'B');
    test.done();
};
```

The above test fails. See output below.

```shell
✖ testOverrideOfFunctions

AssertionError: 'B' == 'A'
    at Object.equal (/usr/local/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.exports.testOverrideOfFunctions (/home/kafoso/git/inherit/test/test.js:142:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodeunit/lib/core.js:236:16)
    at /usr/local/lib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/usr/local/lib/node_modules/nodeunit/lib/core.js:70:9)
    at /usr/local/lib/node_modules/nodeunit/lib/core.js:118:25
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/usr/local/lib/node_modules/nodeunit/deps/async.js:123:13)
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:134:25
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:515:17
```

Naturally, the [`prop` argument should be an Object per your documentation](https://github.com/dfilatov/inherit#creating-a-base-class). However, it would be a nice addition.

**Comment by dfilatov** [comment]
What's the case you need to pass `Function` instead of `Object`?

**Comment by kafoso** [comment]
@dfilatov 
To allow for private variables inside the functions. Example:

```javascript
exports.testInheritedFunctionsWithPrivateVariables = function(test) {
    test.expect(2);
    var A = inherit(function(){
      var _privateVariable = 1;
      this.method = function() {
          return _privateVariable+2;
      };
    });
    var B = inherit(A, function(){
      var _privateVariable = 9;
      this.method = function() {
          return _privateVariable+2;
      };
    });

    test.equal(new A().method(), 3); // Works
    test.equal(new B().method(), 11); // Throws up
    test.done();
};
```

Output:

```shell
✖ testInheritedFunctionsWithPrivateVariables

AssertionError: 3 == 11
    at Object.equal (/usr/local/lib/node_modules/nodeunit/lib/types.js:83:39)
    at Object.exports.testInheritedFunctionsWithPrivateVariables (/home/kafoso/git/inherit/test/test.js:145:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodeunit/lib/core.js:236:16)
    at /usr/local/lib/node_modules/nodeunit/lib/core.js:236:16
    at Object.exports.runTest (/usr/local/lib/node_modules/nodeunit/lib/core.js:70:9)
    at /usr/local/lib/node_modules/nodeunit/lib/core.js:118:25
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/usr/local/lib/node_modules/nodeunit/deps/async.js:123:13)
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:134:25
    at /usr/local/lib/node_modules/nodeunit/deps/async.js:515:17
```

**Comment by zxqfox** [comment]
@kafoso You still do this with __constructor property, isn't it?

```js
exports.testInheritedFunctionsWithPrivateVariables = function(test) {
    test.expect(2);
    var A = inherit(function(){
      var _privateVariable = 1;
      this.method = function() {
          return _privateVariable+2;
      };
    });
    var B = inherit(A, { __constructor: function(){
      this.__base.apply(this, arguments);
      var _privateVariable = 9;
      this.method = function() {
          return _privateVariable+2;
      };
    }});

    test.equal(new A().method(), 3); // Works
    test.equal(new B().method(), 11); // Throws up
    test.done();
};
```

**Comment by zxqfox** [comment]
@dfilatov Do we want this behaviour as a sugar?

**Comment by dfilatov** [comment]
I don't think so. I still don't understand what a sugar is.

**Comment by kafoso** [comment]
> You still can do this with __constructor property, isn't it?

The variable is only available within the constructor's function scope, then. What I'm asking for is private variables, which are available in every function within the "class" Object, but inaccessible from the outside. Entirely like [visibility keywords work in PHP](http://php.net/manual/en/language.oop5.visibility.php), Java and many other high-level programming languages.
